<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['Chinese'] = array (
  'Locale' => 'zh-CN',
  'Name' => 'Chinese Simple(简体中文)',
  'Description' => 'Chinese Simple(简体中文) ,modify by kanbox`s chinese locals file',
  'Version' => '20120415',
  'Author' => 'sarowlwp,Kanbox(first version)',
  'AuthorEmail' => 'sarowlwp@live.cn',
  'AuthorUrl' => 'http://weibo.com/sarowlwp',
  'License' => 'GPL2',
);

//站点名称
$SiteName='Vanilla中文演示';

//////////////////////////////////

// Homepage
$Definition['UserName'] = '用户名';
$Definition['Sign In'] = '登录';
$Definition['Apply for Membership'] = '加入'.$SiteName;
$Definition['Enter your Email address'] = '电子邮件';
$Definition['Enter your Email or Username'] = '电子邮件或用户名';
$Definition['Email or Username'] = '电子邮件或用户名';
$Definition['Request a new password →'] = '获取新密码 →';
$Definition['Sign In →'] = ' 登录 →';
$Definition['Forgot your password?'] = '忘记密码?';
$Definition['Register for Membership'] = '加入'.$SiteName;
$Definition['Registration is currently closed.'] = '注册通道目前关闭。';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = '新手上路，加入请点击其中一个按钮:';
$Definition['Invitation Code'] = '邀请码';
$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = '我同意 <a id="TermsOfService" class="Popup" target="terms" href="%s">服务条款</a>。';
$Definition['Terms of Service'] = '服务条款'; // manuell termsofservice.php bearbeitet; Rest noch offen; besser in definitions.php auslagern
$Definition['ErrorBadInvitationCode'] = '邀请码错误';
$Definition['Name Unavailable'] = '名字无效';
$Definition['Username can only contain letters, numbers, and underscores.'] = '用户名只能包含文字，数字和下划线。';
$Definition['The name you entered is already in use by another member.'] = '名字已存在。';
$Definition['The email you entered in use by another member.'] = '电子邮件地址已存在。'; //doppelt - siehe unten
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'reCAPTCHA 值输入错误，请重新输入。';

$Definition['Passwords don\'t match'] = '密码输入不一致';
$Definition['You must agree to the terms of service.'] = '必须同意服务条款';
$Definition['Sign Up →'] = '登录 →';

$Definition['Powered by %s'] = '技术支持%s';


////////////////////////////////////
// Search
$Definition['Search'] = '搜索';
$Definition['No results for \'%s\''] = '没有符合 \'%s\'的结果';
$Definition['Search results for \'%s\''] = '在结果中搜索 \'%s\'';
$Definition['Comment by %s'] = '%s添加评论';
$Definition['Go'] = '搜索';


////////////////////////////////////
// Activity
$Definition['Activity'] = '新鲜事';
$Definition['Recent Activity'] = '近期动态';
$Definition['%1$s signed in.'] = '%1$s已登录。';
$Definition['%1$s joined.'] = '%1$s加入了'.$SiteName.'，各位列队欢迎';

$Definition['%1$s commented on a discussion.'] = '%1$s 回复了评论';
$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s接受了%4$s的邀请';
$Definition['%3$s approved %2$s membership application.'] = '%3$s批准%2$s的加入申请';
$Definition['%3$s created an account for %1$s.'] = '%3$s为%1$s创建一个帐户';
$Definition['%1$s updated %6$s profile.'] = '%1$s更新%6$s的个人资料';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s记录道%4$s %5$s';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s更改%6$s资料头像';
$Definition['%1$s changed %4$s permissions.'] = '%1$s更改%3$s的权限';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s对%3$s的%8$s添加评论';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s被加入%2$s %3$s组';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s被%2$s %3$s组删除';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s从%2$s组转到%4$s组';
$Definition['You'] = '您';
$Definition['you'] = '您';
$Definition['your'] = '您的';
$Definition['he'] = '他';
$Definition['she'] = '她';
$Definition['his'] = '他的';
$Definition['her'] = '她的';
$Definition['somebody'] = '某人';
$Definition['wall'] = '墙';
$Definition['at'] = '@';
$Definition['dot'] = '.';
$Definition['Comment'] = '评论';
$Definition['Write a comment'] = '写评论';
$Definition['%1$s started a %8$s.'] = '%1$s发表%8$s';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s在%8$s中提到%3$s';
$Definition['%1$s commented on your %8$s.'] = '%1$s对您的%8$s添加评论';
$Definition['%1$s sent you a %8$s.'] = '%1$s向您发送%8$s';
$Definition['message'] = '消息';
$Definition['discussion'] = '帖子';
$Definition['bookmarked discussion'] = '标记的帖子';
$Definition['comment'] = '评论';
$Definition['Not much happening here, yet.'] = '没有多少活动。';
$Definition['Welcome Aboard!'] = '欢迎加入!';

////////////////////////////////////
// General
$Definition['CategoriesViewingAll'] = '现在展示的是'.$SiteName.'中的所有的版块，选择你暂时不想关注的版块【取消关注】，它将不会再出现在你的面板中。';
$Definition['CategoriesShowFollowed'] = '展示我关注的版块';
$Definition['CategoriesViewingFollowed'] = '现在展示的是我关注的版块，还有许多待发掘的版块内容哦！';
$Definition['CategoriesShowUnfollowed'] = '展示我未关注的版块';
$Definition['Unfollow'] = '取消关注';
$Definition['Mark Read'] = '标为已读';
$Definition['Discussions'] = '帖子列表';
$Definition['Dashboard'] = '控制面板';
$Definition['Comments'] = '评论';
$Definition['%s view'] = '%s次浏览';
$Definition['%s views'] = '%s次浏览';
$Definition['%s comment'] = '%s条评论';
$Definition['%s comments'] = '%s条评论';
$Definition['%s new'] = '%s条新消息';
$Definition['Most recent by %1$s'] = '最新评论由%1$s添加';
$Definition['Announcement'] = '置顶';
$Definition['Announcements'] = '置顶帖子';
$Definition['Most recent: %1$s by %2$s'] = '最近更新： %1$s 由 %2$s 添加 ';
$Definition['Inbox'] = '收件箱';
$Definition['New Conversation'] = '新邮件';
$Definition['Conversations'] = '对话';
$Definition['All Conversations'] = '所有邮件';
$Definition['%s message'] = '共%s个对话';
$Definition['%s messages'] = '共%s个对话';
$Definition['Start a New Conversation'] = '写新邮件';
$Definition['Delete Conversation'] = '删除邮件';
$Definition['Recipients'] = '收件人';
$Definition['Start Conversation'] = '发送';
$Definition['Clear Conversation History'] = '清除聊天历史';
$Definition['In this Conversation'] = '在本次对话中';
$Definition['%s and you'] = '%s和您';
$Definition['Add People to this Conversation'] = '添加联系人到本次对话';
$Definition['Add'] = '添加';
$Definition['You do not have any conversations.'] = '目前没有邮件';
$Definition['Add Message'] = '写消息';
$Definition['Send Message'] = '发送消息';
$Definition['Confirm'] = '确定';
$Definition['Are you sure you want to do that?'] = '确定要做此项操作?';
$Definition['Okay'] = '确定';
$Definition['Cancel'] = '取消';

$Definition['All Discussions'] = '所有帖子';
$Definition['You have not started any discussions.'] = '您还没有发表过任何帖子。';
$Definition['Start a New Discussion'] = '我要发帖';
$Definition['New Discussion'] = '新帖子';
$Definition['My Discussions'] = '我的帖子';

$Definition['Add Comment'] = '添加评论';
$Definition['Post Discussion'] = '发表帖子';
$Definition['Post Comment'] = '发表评论';
$Definition['Save Draft'] = '存草稿';

$Definition['Draft saved at %s'] = '草稿已保存 %s';
$Definition['Preview'] = '预览';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = '您在 %2$s 秒内已经发布了 %1$s 次内容。 垃圾信息屏闭功能已开启。 您必须等待 %3$s 秒以后才可以再次发言。';
$Definition['%1$s older comments'] = '%1$s前评论';
$Definition['%1$s more comments'] = '%1$s更多评论';
$Definition['Want to take part in this discussion? Click one of these:'] = '想要加入帖子讨论? 请点击其中之一：';
$Definition['In this Discussion'] = '在本次帖子讨论中';

$Definition['Announce'] = '置顶';
$Definition['Unannounce'] = '取消置顶';
$Definition['Sink'] = '下沉';
$Definition['Unsink'] = '解除下沉';
$Definition['Close'] = '锁定';
$Definition['Reopen'] = '取消锁定';
$Definition['Delete'] = '删除';
$Definition['Delete Discussion'] = '删除帖子';
$Definition['Dismiss'] = '忽略';
$Definition['Edit Comment'] = '编辑评论';

$Definition['Discussion Title'] = '标题';
$Definition['Edit Discussion'] = '编辑帖子';
$Definition['Announce this discussion'] = '发布帖子';
$Definition['Close this discussion'] = '锁定帖子';
$Definition['Sink this discussion'] = '沉贴';

$Definition['Permalink'] = '永久链接';
$Definition['This discussion has been closed.'] = '帖子已锁定';
$Definition['Back to Discussions'] = '返回帖子列表';

$Definition['Howdy, Stranger!'] = '你好，游客!';
$Definition['No discussions were found.'] = '没有帖子!';
$Definition['Sign Out'] = '退出';
$Definition['Hang on a sec while we sign you out.'] = '稍等，正在退出。';
$Definition['Category'] = '版块';
$Definition['Category:'] = '版块:';
$Definition['Categories'] = '版块列表>>';

$Definition['My Drafts'] = '我的草稿';
$Definition['My Bookmarks'] = '我的关注';
$Definition['You do not have any drafts.'] = '没有草稿';
$Definition['Bookmarked Discussions'] = '关注的帖子';
$Definition['You do not have any bookmarks.'] = '未添加关注';
$Definition['Bookmark'] = '添加关注';
$Definition['BookmarkNumberText'] = '关注';
$Definition['Unbookmark'] = '取消关注';


////////////////////////////////////
// Profile

$Definition['More Discussions'] = '更多内容';
$Definition['Notifications'] = '通知';
$Definition['Welcome to Vanilla!'] = '欢迎来到Vanilla!';
$Definition['Change My Picture'] = '更换头像';
$Definition['Change Picture'] = '更换图片';
$Definition['Select an image on your computer (2mb max)'] = '在计算机中选择图片 (最大2MB)';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = '上传文件时请确定您有权发布该图片, 并且不违反服务条款。';
$Definition['Edit My Thumbnail'] = '编辑缩略图';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = '在图像框下拖拽并调整图像大小来定义缩略图图标';
$Definition['Original'] = '原始图';
$Definition['Thumbnail'] = '缩略图';
$Definition['Save'] = '保存';
$Definition['Remove My Picture'] = '删除头像';
$Definition['Remove Picture'] = '删除图片';
$Definition['Your picture has been removed.'] = '头像已删除。';

$Definition['Edit My Account'] = '编辑我的帐户';
$Definition['Edit Account'] = '编辑帐户';
$Definition['Edit User'] = '编辑用户';
$Definition['Username'] = '用户名';
$Definition['Email'] = '电子邮件';
$Definition['Allow other members to see your email?'] = '允许其它用户看到您的电子邮件地址?';
$Definition['Email visible to other users'] = '电子邮件地址公开';
$Definition['Check all roles that apply to this user:'] = '查看此用户的所有权限:';
$Definition['Password Options'] = '密码选项';
$Definition['Reset Password'] = '重设密码';
$Definition['Reset password and send email notification to user'] = '重设密码并向用户发送提醒邮件';
$Definition['Gender'] = '性别';
$Definition['Male'] = '男';
$Definition['Female'] = '女';
$Definition['Change My Password'] = '更改我的密码';
$Definition['Old Password'] = '旧密码';
$Definition['New Password'] = '新密码';
$Definition['Confirm Password'] = '确认密码';
$Definition['Change Password'] = '更改密码';
$Definition['Your old password was incorrect.'] = '旧密码输入有误';
$Definition['Your password has been changed.'] = '密码已更改';

$Definition['My Invitations'] = '我的邀请';
$Definition['You have %s invitations left for this month.'] = '本月您还有  %s 个邀请名额，快去邀请您的好友加入吧';
$Definition['Enter the email address of the person you would like to invite:'] = '输入受邀人的电子邮件地址';
$Definition['Invite'] = '邀请';
$Definition['Sent To'] = '发送给';
$Definition['On'] = '在';
$Definition['Status'] = '状态';
$Definition['Uninvite'] = '未邀请';
$Definition['Send Again'] = '再次发送';
$Definition['Pending'] = '待定';
$Definition['You cannot remove an invitation that has been accepted.'] = '已被接受的邀请不能删除';
$Definition['An invitation has already been sent to the email you entered.'] = '邀请已发送到您输入的邮件地址 ';
$Definition['The email you have entered is already related to an existing account.'] = '您输入的邮件地址已经绑定了一个帐号'; //doppelt - siehe oben
$Definition['You do not have enough invitations left.'] = '您没有足够的邀请';

$Definition['My Preferences'] = '通知设置';
$Definition['Email Notifications'] = '电子邮件通知';
$Definition['Notify me when people write on my wall.'] = '当有人在我的主页留言时通知我';
$Definition['Notify me when people reply to my wall comments.'] = '当有人回复我的帖子时通知我';
$Definition['Notify me of private messages.'] = '有私人消息时通知我';
$Definition['Notify me when I am added to private conversations.'] = '当我被加到私人聊天中时通知我';
$Definition['Notify me when people comment on my discussions.'] = '当有人对我的帖子添加评论时通知我';
$Definition['Notify me when people mention me in discussion titles.'] = '当有人在帖子中提到我时通知我';
$Definition['Notify me when people mention me in comments.'] = '当有人在评论中提到我时通知我';
$Definition['Notify me when people comment on my bookmarked discussions.'] = '当有人对我关注的帖子添加评论时通知我';
$Definition['Save Preferences'] = '保存';
$Definition['Your preferences have been saved.'] = '个性化设置已保存';
$Definition['Your changes have been saved.'] = '更改已保存';
$Definition['Your changes have been saved successfully.'] = '更改保存成功'; // eines davon in github löschen
$Definition['Send %s a Message'] = '向%s发送消息';

$Definition['About'] = '关于';
$Definition['Name'] = '名字';
$Definition['Joined'] = '加入';
$Definition['Visits'] = '访问';
$Definition['Last Active'] = '上次在线';
$Definition['Roles'] = '身份';
$Definition['Write something about yourself...'] = '个人简介...';

$Definition['Password'] = '密码';
$Definition['Remember me on this computer'] = '本机记住登录状态';
$Definition['or'] = '或';
$Definition['Clear'] = '删除';
$Definition['Share'] = '发布';
$Definition['Enter your email address or username'] = '请输入您的邮箱或用户名来帮助我们确认您的身份';

$Definition['Reset my password'] = '重置我的密码';
$Definition['Could not instantiate mail function.'] = '邮件服务异常，请联系管理员';
$Definition['Request a new password'] = '请求一个新的密码';
$Definition['ValidateRegex '] = '格式不正确';
$Definition['ValidateRequired'] = '内容不能为空';
$Definition['ValidateRequiredArray'] = '数组验证';
$Definition['ValidateEmail'] = '电子邮箱格式不正确';
$Definition['Email Unavailable'] = '该邮箱已被占用';
$Definition['Sign Up'] = '注册';
$Definition['ValidateDate'] = '日期验证';
$Definition['ValidateInteger'] = '整数验证';
$Definition['ValidateBoolean'] = '布尔验证';
$Definition['ValidateDecimal'] = '小数验证';
$Definition['ValidateTime'] = '时间验证';
$Definition['ValidateTimestamp'] = '时间标记验证';
$Definition['ValidateUsername '] = '用户名验证 用户名必须由3-20个字母，数字和下划线组成';
$Definition['ValidateLength'] = '长度不正确';
$Definition['ValidateEnum'] = '列举型验证';
$Definition['ValidateOneOrMoreArrayItemRequired'] = '验证一个或多个数组中的项';
$Definition['ValidateConnection '] = '连接验证 您指定的参数无法与数据库建立连接。 数据库返回如下错误： <code>%s</code>';
$Definition['ValidateMinimumAge'] = '最低年龄验证';
$Definition['ValidateMatch'] = '请确认密码';

$Definition['ErrorPermission'] = '你没有该权限';
$Definition['ErrorCredentials'] = '用户名或密码错误，请重新输入';
$Definition['ErrorPluginVersionMatch'] = '插件版本错误。可用插件{0} V1不符合版本要求({2})';
$Definition['ErrorPluginDisableRequired'] = '错误终止插件命令。插件{1}需要基于插件{0}运行，插件{0}不能终止';
$Definition['ErrorPluginEnableRequired'] = '错误调用插件命令。这个插件需要{ 0 }插件被打开后才可以使用';
$Definition['ErrorTermsOfService'] = '服务条款错误。您必须同意服务条款';
$Definition['ErrorRecordNotFound'] = '找不到记录错误。要求的记录找不到';

$Definition['PageDetailsMessageFull'] = '页面详情消息已满';
$Definition['PageDetailsMessage'] = '页面详情消息';
$Definition['RoleID'] = '身份编号';
$Definition['Garden.Registration.DefaultRoles'] = '花园。注册。默认身份';
$Definition['Garden.Title'] = '花园。标题';
$Definition['Garden.Email.SupportName'] = '花园。电子邮件。支持名字';
$Definition['Garden.Email.SupportAddress'] = '花园。电子邮件。支持地址';
$Definition['UrlCode'] = 'URL代码';
$Definition['OldPassword'] = '旧密码';
$Definition['Latest %1$s'] = '最后修改 %1$s';
$Definition['RoleID'] = '身份编号';

$Definition['A message has been sent to your email address with password reset instructions.'] = '重置密码信息已经发送到您的邮箱，请您注意查收！';
$Definition['[%s] Confirm Your Email Address'] = '[%s] 请确认你的邮箱地址'; 
$Definition['EmailConfirmEmail'] = '你好！

'.$SiteName.'请您确认您在'.$SiteName.'的帐户邮箱，只有确认的账户才能成为'.$SiteName.'的正式成员，账户邮箱将作为您重置密码，收取提醒消息等一系列的功能的前提，请确认邮箱的正确性。

请点击下面的链接进行确认: {/entry/emailconfirm,url,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';

$Definition['EmailInvitation'] = '你好!

    这是来自'.$SiteName.'的邀请信

	您的好友 %1$s 邀请你加入 %2$s. 欢迎点击下面链接的成为'.$SiteName.'的一员:
	

	  %3$s

        
		'.$SiteName.'社区是针对青海大学学子的BBS社区，我们致力于给您带来一个方便快捷的交流平台，如果您在使用中有什么疑问，或者建议，欢迎到 【我要提建议】 区发帖，'.$SiteName.'感谢您的支持。
         
        我们的口号是：让师弟认识学姐，让师兄认识学妹
        我们的目标是：让青海大学人，有一个自己的网上家园
        
        感谢您的支持！

	  '.$SiteName.'祝您开心每一天!';
$Definition['EmailMembershipApproved'] = '你好： %1$s,

    这是来自'.$SiteName.'的通知信

	恭喜您，你的申请已被管理员通过，欢迎加入'.$SiteName.'. 点击下面的链接进行登录:

	  %2$s
	    
	  '.$SiteName.'祝你开心每一天!';
$Definition['EmailNotification'] = '%1$s

	这是来自'.$SiteName.'的密码重置通知

	Follow the link below to check it out:
	%2$s

	'.$SiteName.'祝你开心每一天!';
$Definition['EmailPassword'] = '你好 %1$s,

	这是来自'.$SiteName.'的密码重置通知

	%2$s 的密码已经被您重置 %3$s. 请使用系统随机的密码登录并修改您的密码:       

	  Email: %6$s
	  Password: %5$s
	  Url: %4$s

	      '.$SiteName.'祝你开心每一天!';
$Definition['EmailStoryNotification'] = '%1$s

	%3$s

	---
	请点击下面的链接查看消息:
	%2$s

	如果此邮件对您造成了影响，请您登陆社区，进入个人主页，通知设置中取消邮件通知的勾选。
	
	      例如 用户名为guest
	      登陆社区->点击工具条guest->通知设置->取消相应选项的勾选
	
	'.$SiteName.'祝你开心每一天!';
$Definition['EmailWelcome'] = '你好 %1$s,

    这是来自'.$SiteName.'的欢迎信
    
	%2$s 已经为您创建了'.$SiteName.'的账户 %3$s. 请使用以下信息登录:

	  Email: %6$s
	  Password: %5$s
	  Url: %4$s

'.$SiteName.'社区是针对青海大学学子的BBS社区，我们致力于给您带来一个方便快捷的交流平台，如果您在使用中有什么疑问，或者建议，欢迎到我要提建议区发帖，'.$SiteName.'感谢您的支持。
         
        我们的口号是：让师弟认识学姐，让师兄认识学妹
        我们的目标是：让青海大学人，有一个自己的网上家园
        
        感谢您的支持！

	      '.$SiteName.'祝你开心每一天!';
$Definition['EmailWelcomeConnect'] = '你好 {User.Name},

	You have successfully connected to {Title}. Here is your information:

	  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

'.$SiteName.'祝你开心每一天!';
$Definition['EmailWelcomeRegister'] = '您好 {User.Name},

	恭喜您，成功注册了{Title} 账号. 以下是您的注册信息:

	  用户名: {User.Name}
          邮件: {User.Email}

        '.$SiteName.'社区是针对青海大学学子的BBS社区，我们致力于给您带来一个方便快捷的交流平台，如果您在使用中有什么疑问，或者建议，欢迎到我要提建议区发帖，'.$SiteName.'感谢您的支持。
         
        我们的口号是：让师弟认识学姐，让师兄认识学妹
        我们的目标是：让青海大学人，有一个自己的网上家园
        
        感谢您的支持！

        访问地址 {/,url,domain}.

';

$Definition['PasswordRequest'] = '你好，我们收到对您 %2$s 帐户的密码重置申请 . 如果您需要重置密码，请点击下面的链接进行:

%3$s

如果这不是您本人的重置申请，请忽略这封Email.';

$Definition['EmailHeader'] = '你好 {User.Name}!
';
$Definition['EmailFooter'] = '祝你开心每一天!';

$Definition['Use the content at this url as your homepage.'] = '默认首页，当用户访问 <strong>%s</strong>时，默认展现的页面，vanilla默认使用 "All Discussions" 页作为默认首页，你可以根据你的喜好来设置你的默认首页。';

$Definition['Category Management'] = '版块管理';
$Definition['All Categories'] = '所有版块';
$Definition['Categories &amp; Discussions'] = '版块 & 帖子';
$Definition['Manage Plugins'] = '插件管理';
$Definition['PluginHelp'] = "vanilla提供了一个强大的插件系统，能够帮您增加一些有用的功能，例如增加投票，美化模板等等，vanilla默认有很多插件，如果你想好获得更多的插件，请点击这里 <a href=\"http://vanillaforums.org/addons\">获取插件</a> ，从官网获取";
$Definition['ApplicationHelp'] = "应用帮助。 您可以添加更多应用功能。<br />应用功能被加入到文件夹 %s,您可以在这里激活或关闭它"; 
$Definition['ThemeHelp'] = "和wordpress类似，vanilla也提供了强大的模板功能，你可以从官网下载模板文件，然后解压到 %s 文件夹，在后台你就能够看到模板选项，点击启用即可完成美化.";
$Definition['AddonProblems'] = "加载项问题<h2>Probleme?</h2><p>Läuft etwas schief mit einem Add-On? Wen dem so ist kannst du bestimmte Bereich deines Forums wahrscheinlich nicht nutzen. Deaktiviere sie manuell hier:</p>%s";
$Definition['Date.DefaultFormat'] = '%Y年%m月%d日';
$Definition['Date.DefaultDayFormat'] = 'dd';
$Definition['Date.DefaultYearFormat'] = '%Y年%m月%d日';
$Definition['Date.DefaultTimeFormat'] = 'hh:mm:ss';
$Definition['Saved'] = '保存';

////////////////////////////////////
// Plugin Vanilla Replies
$Definition['Reply'] = '回复';
$Definition['Replies'] = '全部回复';
$Definition['Write a reply'] = '写回复';
$Definition['%s Reply'] = '回复';
$Definition['%s Replies'] = '全部回复';
$Definition['Show 1 more reply...'] = '再显示一条回复...';
$Definition['Show %s more replies...'] = '显示更多回复...';
$Definition['1$s replied to %4$s %8$s.'] = '%1$s回复%4$s %8$s.'; // bei Profile Activity; geht nicht


////////////////////////////////////
// Dashboard Menu
$Definition['← Visit Site'] = '← 访问网站';
$Definition['Site Settings'] = '网站设置';
$Definition['General'] = '全部';
$Definition['Routes'] = '路径';
$Definition['Messages'] = '消息';
$Definition['Import'] = '导入';
$Definition['Banner'] = '导航';
$Definition['Settings'] = '设置';
$Definition['Authentication'] = '认证';
$Definition['Homepage'] = '首页';
$Definition['Addons'] = '加载项';
$Definition['Applications'] = '应用';
$Definition['Plugins'] = '插件';
$Definition['Forum Settings'] = '论坛设置';
$Definition['Flood Control'] = '流量控制';
$Definition['Moderation'] = '审计';
$Definition['Themes'] = '模板';
$Definition['Locales'] = '国际化';
$Definition['Statistics'] = '统计';
$Definition['Roles & Permissions'] = '身份&权限';
$Definition['Registration'] = '注册';
$Definition['Advanced'] = '高级';
$Definition['Forum'] = '论坛设置';
$Definition['Edit/Delete Log'] = '编辑/删除 日志';

////////////////////////////////////
// Dashboard Buzz
$Definition["What's the Buzz?"] = '网站动态';
$Definition['Recently Active Users'] = '近期活跃的用户';
$Definition['Users'] = '用户';
$Definition['New users in the last day'] = '昨天注册的新用户';
$Definition['New users in the last week'] = '上周注册的新用户';
$Definition['New conversations in the last day'] = '昨天的新对话';
$Definition['New conversations in the last week'] = '上周的新对话';
$Definition['Conversation Messages'] = '对话消息';
$Definition['New messages in the last day'] = '昨天的新消息';
$Definition['New messages in the last week'] = '上周的新消息';
$Definition['New discussions in the last day'] = '昨天的新帖子';
$Definition['New discussions in the last week'] = '上周的新帖子';
$Definition['New comments in the last day'] = '昨天的新帖子';
$Definition['New comments in the last week'] = '上周的新帖子';

////////////////////////////////////
// Dashboard 外观
$Definition['Apply'] = '启用';
$Definition['Get More Themes'] = '从vanilla官方获取模板';
$Definition['Manage Themes'] = '帖子管理';
$Definition['Current Theme'] = '正在使用的模板';
$Definition['Other Themes'] = '其他可用模板';
$Definition['All Pages'] = '所有页面（*）';
$Definition['All Forum Pages'] = '所有论坛讨论区页面';
$Definition['Enter the url to the page you would like to use as your homepage:'] = '输入你想要做为默认页（首页）的url地址：';
$Definition['Banner Title'] = '站点名';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = '站点名将显示在导航栏的最左边，如果用户上传了站点LOGO，那么将用LOGO代替';
$Definition['Banner Logo'] = '站点Logo';
$Definition['The banner logo appears at the top of your forum.'] = '站点LOGO将显示在论坛顶部';
$Definition['Messages can appear anywhere in your application.'] = '消息系统用来在应用的各个地方展示通知，可以用来向用户发布通知和新闻，例如重大更新，重大事件的发生等，在这里，你可以方便的管理你的消息';


////////////////////////////////////
// Dashboard 论坛设置
$Definition['Organize Categories'] = '版块管理';
$Definition['Manage Categories'] = '论坛版块管理';
$Definition['Add Category'] = '添加版块';
$Definition['Don\'t use Categories'] = '停用版块';
$Definition['Category Page Layout'] = '版块展示方式';
$Definition['Only Allow Each User To Post'] = '允许每个用户发布';
$Definition['Within'] = '在有限时间内';
$Definition['Or Spamblock For'] = '否则阻止发布';
$Definition['discussion(s)'] = '帖子';
$Definition['comment(s)'] = '评论';
$Definition['seconds'] = '秒';
$Definition['minute(s)'] = '分钟';

////////////////////////////////////
// Dashboard Users

$Definition['Manage Users'] = '管理用户';
$Definition['Add User'] = '添加用户';
$Definition['%s user(s) found.'] = '共%s位用户';
$Definition['First Visit'] = '首次访问';
$Definition['Last Visit'] = '上次访问';
$Definition['Options'] = '选项';
$Definition['Edit'] = '编辑';
$Definition['Generate Password'] = '生成密码';
$Definition['Reveal Password'] = '显示密码';
$Definition['User Registration Settings'] = '用户注册设置';
$Definition['Method'] = '注册方式';
$Definition['Basic'] = '基础方式';
$Definition['Approval'] = '审核方式';
$Definition['Invitation'] = '邀请方式';
$Definition['New users fill out a simple form and are granted access immediately.'] = '新用户只需要填写一个简单的表单就立刻注册成功';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = '新用户需要提交申请，由管理员负责审核';
$Definition['Existing members send invitations to new members.'] = '老用户邀请新用户方式';
$Definition[' Require users to confirm their email addresses (recommended)']='需要用户确认邮件地址（推荐启用）';
$Definition['Confirm Email'] = '邮箱确认';
$Definition['Key Type'] = 'Captcha 密钥类型';
$Definition['Key Value'] = 'Captcha 密钥值';
$Definition['Change the way that new users register with the site.'] = '选择新用户注册方式';
$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:'] = '
基础注册方式需要用户填写一个验证码来防止垃圾用户产生，你需要获取一个recaptcha.net的账户，注册这个账号是免费的，注册登录后获取一个Captcha私钥和密钥，
然后继续下面的设置。vanilla的验证码没有自己实现，而是通过调用recaptcha.net的开放接口实现的';
$Definition['Your request has been sent. Check your email for further instructions.'] = '确认信已发出，请到您的邮箱中查收';
$Definition['Email Confirmation Role'] = '邮箱确认角色';
$Definition['Users will be assigned to this role until they\'ve confirmed their email addresses.'] = '新注册的用户将被设置为此角色，直到他们激活（收到确认信）';
////////////////////////////////////
// Dashboard Settings
$Definition['General Settings'] = '常规设置';
$Definition['Language'] = '语言';
$Definition['Application Title'] = '应用标题';
$Definition["Use Garden's .htaccess file to rewrite urls"] = '使用Garden\'s .htaccess 重写URL'; //--> geht nicht
$Definition['The server configuration for this setting could not be found. If you enable this setting your site may become unavailable.'] = '服务器的此项设置找不到。如果您仍使用此项设置，您的网站将不可用。'; //--> geht nicht
$Definition['Email sent from the application will be addressed from the following name and address'] = '应用程序将会按照以下的名字和地址发送电子邮件。';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = '我们将按默认设置使用本地邮件服务器。如果您想使用其它STMP 邮件服务器，请在下面设置。';
$Definition['Use an SMTP server to send email'] = '使用STMP服务器发送邮件'; //--> geht nicht

$Definition['Manage Routes'] = '管理路径';
$Definition['Add Route'] = '添加路径'; //--> geht nicht, ev. wegen URL
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = '路径会根据URL将用户转接到网站的不同端口'; //--> geht nicht, ev. wegen URL die noch folgt
$Definition['Route'] = '路径';
$Definition['Target'] = '目标';
$Definition['Type'] = '类型';
$Definition['Edit'] = '编辑'; //--> geht nicht, ev. wegen URL
$Definition['Route Expression'] = '路径展示';

$Definition['Manage Messages'] = '管理消息';
$Definition['Add Message'] = '写消息'; //--> geht nicht, ev. wegen URL
$Definition['Messages can appear anywhere in your application, and can be used to inform your users of news and events. Use this page to re-organize your messages by dragging them up or down.'] = '消息可以出现在应用程序中的任何位置。消息可以用来告诉用户新闻和事件。使用本页,通过拖放它们上升或下降来重组你的消息';
$Definition['Edit Message'] = '编辑消息';
$Definition['Location'] = '位置';
$Definition['Message'] = '消息';
$Definition['Disabled'] = '关闭'; //--> geht nicht, ev. wegen URL
$Definition['Delete'] = '删除'; //--> geht nicht, ev. wegen URL
$Definition['Page'] = '页';
$Definition['Every Page'] = '每页';
$Definition['Profile Page'] = '资料页';
$Definition['Discussions Page'] = '帖子页';
$Definition['Comments Page'] = '评论页';
$Definition['Position'] = '位置';
$Definition['Above Main Content'] = '在主内容以上';
$Definition['Below Sidebar'] = '在工具条以下';
$Definition['Appearance'] = '外观';
$Definition['Information'] = '信息';
$Definition['Warning'] = '警告';
$Definition['Panel Box'] = '面板箱';
$Definition['None'] = '没有';
$Definition['Allow users to dismiss this message'] = '允许用户撤消该消息'; //--> geht nicht
$Definition['Enable this message'] = '激活消息'; //--> geht nicht

$Definition['Manage Applications'] = '管理应用';
$Definition['All'] = '全选';
$Definition['Enabled'] = '激活'; //--> geht nicht, ev. wegen URL
$Definition['Application'] = '应用';
$Definition['Description'] = '描述';
$Definition['Disable'] = '关闭';
$Definition['Version'] = '版本';
$Definition['By'] = '被';
$Definition['Visit Site'] = '访问网站';


////////////////////////////////////
// System & Error Messages
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = '处理请求时发生致命错误。服务器返回如下内容: %s';
$Definition['The invitation was sent successfully.'] = '邀请发送成功';
$Definition['Your invitation has been sent.'] = '邀请已发送'; // evtl. raus
$Definition['The invitation was removed successfully.'] = '邀请已成功删除';
$Definition['Although the invitation was created successfully, the email failed to send. The server reported the following error: %s'] = '邀请创建成功，但邮件无法送达。服务器抛如下错误信息: %s';
$Definition['You must be authenticated in order to use this form.'] = '您必须经过验证才可以使用此表';


////////////////////////////////////
// System E-Mail
$Definition['[%s] Password Reset Request'] = '[%s]重设密码请求';
$Definition['[%s] Invitation'] = '[%s]邀请';
$Definition['[%s] Welcome Aboard!'] = '[%s]欢迎登录！';
$Definition['[%s] Password Reset'] = '[%s]重设密码';

/**
 * PLUGINS
 */
$Definition['Online'] = '在线';
$Definition['Offline'] = '已下线';
$Definition['Pockets'] = '口袋（自定义HTML块）';
$Definition['Show Pocket Locations'] = '显示可自定义HTML块及其位置';
$Definition['Add Pocket'] = '添加一个自定义HTML位置';
$Definition['Edit Thumbnail'] = '编辑缩略图';
$Definition[ 'Questions tagged with \'%s\''] = '和标签 “ %s ” 相关的帖子';
$Definition[ 'Tagged with '] = '标签为 ';
$Definition['No items tagged with %s.'] = '没有和标签 “ %s ” 相关的帖子';
$Definition['Whos Online'] = '看看谁在线';
$Definition['Where should the plugin be shown?'] = '在哪里可以显示插件？';
$Definition['Whos Online'] = '看看谁在线';
$Definition['Who\'s Online Settings'] = '在线状态设置';
$Definition['Who\'s Online'] = '看看谁在线';
$Definition['Make me invisible? (Will not show you on the list)'] = '在线对其他用户不可见（你将不会出现在在线列表中）';
$Definition['%s said'] = '%s说到';
$Definition['Signature Settings'] = '签名设置';
$Definition['Flag'] = '举报';
$Definition['Whos Online'] = '在线用户';
$Definition['Voting'] = '投票';
$Definition['Tagging'] = '标签';
$Definition['Sections'] = '选项';
$Definition['Every'] = '每次';
$Definition['Discussion'] = '只在帖子页';
$Definition['Frequency'] = '频率';
$Definition['Rate of refresh'] = '间隔时间';
$Definition['In seconds'] = '秒';
$Definition['Top Posters'] = '英雄榜';
$Definition['Mark All Viewed'] = '忽略新消息';
$Definition['Hide signatures?'] = '隐藏签名？';
$Definition['Strip images out of signatures?'] = '屏蔽所有带图片的个性签名？';
$Definition['Signature Code'] = '在这里键入你的签名';
$Definition['Signatures'] = '签名';
$Definition['Disable Signatures'] = '关闭个性签名';
$Definition['Enable Signatures'] = '开启个性签名';
$Definition['Media'] = '上传管理（富媒体）';
$Definition['FileUpload is currently ON'] = 'FileUpload 插件打开状态';
$Definition['FileUpload is currently OFF'] = 'FileUpload 插件关闭状态';
$Definition['Turn ON'] = '启用插件';
$Definition['Turn OFF'] = '关闭插件';
$Definition['This plugin enables uploading files and attaching them to discussions and comments.'] = '这个插件能够提供文件上传的功能，帖子内容和评论中都可以嵌入附件';
$Definition['Permissions'] = '权限管理';
$Definition['Ban List'] = '黑名单';
$Definition['Flagging Settings'] = '标记设置';
$Definition['Create Discussions'] = '创建一个帖子（如果设置，则每次标记帖子后，都会自动创建一个名为FLAG：xxx的帖子[不建议启用]）';
$Definition['Flagged Items'] = '所有标记条目';
$Definition['Take Action'] = '立刻去处理';
$Definition['Stop Forum Spam Settings'] = '防灌水设置';
$Definition['Flag this Discussion'] = '举报这个帖子';
$Definition['Flag this Comment'] = '举报这条评论';
$Definition['Reason'] = '请添加举报原因';
$Definition['Flag this!'] = '我要举报！';
$Definition['Link to content:'] = '文章链接';
$Definition['Notify me when a comment is flagged.'] = '当我的评论被举报时通知我';
$Definition['FlagLinkContent'] = '内容链接';

$Definition['FlagForReview'] = '你对这条内容的举报将会被管理员处理，如果你确定要做到这一点，请输入一个简短的原因，然后按下举报！请不要恶意举报，多次恶意举报用户将会被封号，感谢您的支持';

//Quotes
$Definition['Quote'] = '回复';
$Definition['%s said:'] = '%s :';
$Definition['Quote Settings'] = '回复设置';
$Definition['Quotes Settings'] = '回复设置';
$Definition['Quote Folding'] = '回复内容折叠设置';
$Definition['How many levels deep should we start folding up quote trees?'] = '设置展示回复内容的方式，默认仅展示你回复的内容';
$Definition['Don\'t ever fold quotes'] = '展示所有回复内容';
$Definition['One level deep'] = '仅展示我回复的内容';
$Definition['Two levels deep'] = '展示两级回复内容';
$Definition['Three levels deep'] = '展示三级回复内容';
$Definition['Four levels deep'] = '展示四级回复内容';
$Definition['Five levels deep'] = '展示五级回复内容';

//Like
$Definition['Like'] = '我喜欢';
$Definition['Unlike'] = '不喜欢';
$Definition[' Like'] = ' 次喜欢';
$Definition[' Likes'] = ' 次喜欢';
//Karma bank
$Definition['Newer'] = '前一页'; 
$Definition['Older'] = '后一页';
$Definition['ILiked'] = '内容表态奖励积分';
$Definition['Liked'] = '优质内容奖励积分';
$Definition['CountVisits'] = '登陆奖励积分';
$Definition['CountComments'] = '评论奖励积分';
$Definition['CountDiscussions'] = '发帖奖励积分';
$Definition['QnACountAccept'] = '提问回到被采纳奖励积分';
$Definition['QnACountAcceptance'] = '接收答案奖励积分';
$Definition['Rewards'] = '发放积分';
$Definition['Reason'] = '奖励原因';
$Definition['Amount'] = '数量';
$Definition['Karma Bank'] = '积分';
$Definition['Karma Balance'] = '积分记录';
$Definition['Starting'] = '注册';
$Definition['Balance'] = '积分';
$Definition['KARMA BANK'] = '积分银行';
$Definition['You do not have any Karma yet.'] = '你还没有获得任何积分，请加油吧';
$Definition['%s\'s Karma Balance'] = '%s的积分记录';
$Definition['&laquo; Back to Profile'] = '&laquo; 回到个人资料页面';
$Definition['Transaction'] = '明细';
$Definition['Date'] = '日期';
$Definition['Reward / Tax'] = '添加奖励 奖励 / 税负';
$Definition['Karma'] = '积分';
$Definition['%01.2f Karma'] = '%01.2f 积分';

//error Page
$Definition['Page Not Found'] = '页面不存在';
$Definition['The page you were looking for could not be found.'] = '你所访问的页面不在家，全家都去火星了'; 
$Definition['PermissionErrorTitle'] = '权限不足';
$Definition['PermissionErrorMessage'] = '你没有该权限哦，需要的话找管理审核吧'; 
$Definition['Deleted'] = '页面不存在';
$Definition['The content you were looking for has been deleted.'] = '你所访问的页面不在家，全家都去火星了';

//邮件插件
$Definition['Your message was successfully sent.'] = '邮件发送成功.';
$Definition['Mass Delivery'] = '全员信';
$Definition['Subject'] = '主题';
$Definition['Body'] = '内容';
$Definition['Send only to:'] = '仅发送到:';
$Definition['Options:'] = '选项:';
$Definition['Send me only'] = '仅发送给我';
$Definition['Use command line (cron)'] = 'Use command line (cron)';
$Definition['Your message will be sent to %d recipient'] = '你将要发送 %d 封邮件';
$Definition['Your message will be sent to %d recipients'] = '你将要发送 %d 封邮件';
$Definition['Confirm'] = '确认';
$Definition['Send'] = '发送';
$Definition['RecipientEmailList'] = 'Dummy Email';
$Definition['No one to send'] = 'No one to send';

//问答插件
$Definition['Unanswered Questions'] ='等待回答的问题';
$Definition['answer'] ='答案';
$Definition['Accept'] ='采纳';
$Definition['Reject'] ='不采纳';
$Definition['Accept this answer.'] ='采纳为最佳答案。';
$Definition['Reject this answer.'] ='不采纳该回答。';
$Definition['Click accept or reject beside an answer.'] ='尊重他人回答，请选择 “采纳” 或 “不采纳” 进行评价。';
$Definition['QnA Rejected Answer'] ='  未被采纳的答案';
$Definition['QnA Accepted Answer'] ='  已被采纳为最佳答案√';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] ='有人回答了你的提问。你需要去检查他的回答 采纳/不采纳';
$Definition['This question\'s answer has been accepted.'] ='该提问的回答被采纳';
$Definition['Q&A $QnA'] ='$QnA 这里注意一下!!--2';
$Definition['You\'ve asked questions that have now been answered'] ='<a href={/discussions/mine?qna=Answered,url}>你提问的问题有人回应了</a>. 请及时对回答进行评价.';

$Definition['You can either ask a question or start a discussion.']='发起一个提问，说出你心中的不解，让大家解答你心中的烦恼;<br>发表一篇帖子，写下自己的见闻，分享你的感受~~  
<br>'.$SiteName.'发帖规则发布，不定期更新，敬请阅读<a href="http://www.aiqingda.com/discussion/158"> '.$SiteName.'发帖规则 </a>
<br>提示：请不要发布类似[天气不错][....]的帖子，高质量的帖子对你，对阅读者都是一种享受，'.$SiteName.'感谢您的理解。';
$Definition['Question Title']='问题主题';
$Definition['Discussion Title']='讨论主题';
$Definition['Ask Question']='提问';
$Definition['Post Discussion']='提交';
$Definition['Ask a Question']='我要提问题';

$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s 回答了 %4$s %8$s.';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s 接受了 %4$s %8$s.';
$Definition['Q&A Accepted'] = '已解决√';
$Definition['Q&A Answered'] = '已回答';
$Definition['Q&A Question'] = '提问';

//你对标记为主持人审查。如果你确定要做到这一点，请输入下面一个简短的原因，然后按“国旗！”。


////////////////////////////////////
// Dashboard Gemeldete Inhalte
$Definition['Flagged Content'] = '标记内容';
$Definition['The following content has been flagged by users for moderator review.'] = '用户标记了以下内容给版主.';
$Definition['Enable Content Flagging'] = '标记开启';
$Definition['Content Flagging'] = '内容标记';


////////////////////////////////////
// New Definitions that need to be sorted
$Definition['Add a Comment'] = '添加评论';
$Definition['Write Comment'] = '写评论';
$Definition['Save Comment'] = '保存评论';
$Definition['Invited by'] = '邀请';
$Definition['Delete Account'] = '删除帐号';
$Definition['Edit Preferences'] = '编辑首选项';
$Definition['Started by %1$s'] = '由%1$s更新';
$Definition['Outgoing Email'] = '邮件';

$Definition['Max Comment Length'] = '评论字数上限';

$Definition['Discussions per Page'] = '每页帖子';
$Definition['Comments per Page'] = '每页的评论';
$Definition['Refresh Comments'] = '刷新评论';
$Definition['Archive Discussions'] = '帖子存档';


$Definition['Date.DefaultTimeFormat'] = '%H:%M';
$Definition['Date.DefaultDayFormat'] = '%m月%e日 ';

//lastComment
$Definition['Latest Commented'] = '最新评论帖';

//times ago [Time format] 
$Definition['just now'] = '刚刚';
$Definition['a few minutes ago'] = '几分钟前';
$Definition['%s minutes ago'] = '%s 分钟前';
$Definition['less than an hour ago'] = '不到1小时前';
$Definition['today at %s'] = '今天 %s';
$Definition['yesterday around %s'] = '昨天 %s';
$Definition[' morning'] = ' 清晨';
$Definition[' afternoon'] = ' 午后';
$Definition[' night'] = ' 午夜';
$Definition[' evening'] = ' 晚上';
$Definition['about a week ago'] = '一周前';
$Definition['about two weeks ago'] = '两周前';
$Definition['about three weeks ago'] = '三周前';
$Definition['about %s month%s ago'] = '%s 月前';
$Definition['about %s year%s ago'] = '%s 年前';
$Definition['%s second'] = '%s 秒';
$Definition['%s seconds'] = '%s 秒';
$Definition['%s minute'] = '%s 分钟';
$Definition['%s minutes'] = '%s 分钟';
$Definition['%s hour'] = '%s 小时';
$Definition['%s hours'] = '%s 小时';
$Definition['%s day'] = '%s 天';
$Definition['%s days'] = '%s 天';
$Definition['%s week'] = '%s 周';
$Definition['%s weeks'] = '%s 周';
$Definition['%s month'] = '%s 月';
$Definition['%s months'] = '%s 月';
$Definition['%s year'] = '%s 年';
$Definition['%s years'] = '%s 年';
$Definition[' ago'] = '前';

//新增翻译项
$Definition['ConnectCreateAccount'] = '连接登陆信息';
$Definition['ConnectLeaveBlank'] = '请输入占有此昵称帐号的密码进行绑定.';
$Definition['ConnectChooseName'] = '请输入用户名，如果您是老用户，请输入原有用户名，并输入原有帐号密码进行绑定.';
$Definition['Or you can...'] = '其他方式';
$Definition['ConnectExistingPassword'] ='请输入原有账号的密码进行绑定，如果你是新用户，则该用户名已被使用，请选择另一个';
$Definition['Other'] = '其他';
$Definition['Sign In with TecentQQ'] = '使用QQ登陆';

//QQ登录
$Definition['Hang on a sec while we sign you out.'] = '正在退出，请稍等';
$Definition['You are attempting to sign out of Vanilla. Are you sure you want to %s?'] = '你将要离开'.$SiteName.'，你确定要 %s 吗？';
$Definition['sign out'] = '退出';
$Definition['You are signed out.'] = '退出成功';
$Definition['Closed'] = '结贴';
$Definition['Tags'] = '标签';
$Definition['Register IP']='注册IP';
$Definition['Last IP']='最后登录IP';
$Definition['Notify me when people start new discussions.']='当有人发布新帖子时通知我';
$Definition['Notify me when people comment on a discussion.']='当有人评论一个帖子时通知我';
$Definition['Popup'] = '站内提醒';
$Definition['Commenting not allowed.'] = '评论已经关闭';
$Definition['Forgot?']='忘记密码';
$Definition['Keep me signed in']='记住登录状态';
$Definition['Security Check'] = '验证码';
$Definition['Enter your Email address or username'] = 'Email/用户名';
$Definition['Email/Username'] = 'Email/用户名';
$Definition["Don't have an account? %s"]='还没有账号？%s';
$Definition['Create One.']='立即注册';
$Definition["GuestModule.Message"]='貌似这位童鞋你是新来的吧？点下面的链接加入'.$SiteName.'吧 ~ ';
$Definition['%s New']='%s';
$Definition['%s New Plural']='%s';
$Definition['Delete'] = '删除';
$Definition['Activity.Delete'] = '删除';

$Definition['More'] = '更多';
$Definition['Popular'] = '最热门的';
$Definition['Vote'] = '投票';
$Definition['Views'] = '浏览';
$Definition['Popular Tags'] = '热门标签';
$Definition['Discussions'] = '所有帖子';
$Definition['inbox'] = '收件箱';
$Definition['sorted by'] = '排序方式';
$Definition['Votes'] = '投票数';
$Definition['Date Added'] = '添加时间';
$Definition['Unannounce'] = '取消置顶';
$Definition['Sink'] = '下沉';
$Definition['Delete Discussion'] = '删除帖子';
$Definition['Tagged'] = '此帖子使用的标签';
$Definition['Follow'] = '关注';
$Definition['Follows'] = '关注';
$Definition['Activity.Comment'] = '评论';

$Definition['Uploading...'] = '上传中...';
$Definition['Insert Image'] = '插入图片';
$Definition['Attach a file'] = '添加图片';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = '点击查看原始图片';
$Definition['Attachments'] = '附件';

$Definition['Redirecting...'] = '正在跳转...';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = '请稍候,如果没有跳转请<a href="%s">点击此处</a>手动跳转.';
$Definition['Add Info &amp; Create Account'] = '起个昵称吧';
$Definition['Choose a name to identify yourself on the site.'] = '输入您在论坛里显示的用户名';
$Definition['Connect'] = '确定';
$Definition['You must set a name!'] = '请输入用户名';
$Definition['This name is already used!'] = '此用户名已经存在';
$Definition['Sign in'] = '登录';
$Definition['I remember now!'] = '我想起来了!';

$Definition['This email is already used!'] = '此邮件已经使用';
$Definition['You do not have any notifications yet.'] = '目前没有通知';
$Definition['Add Item'] = '添加屏蔽项';
$Definition['Blocked'] = '传送门';
$Definition['Added By'] = '添加人';
$Definition['Notes'] = '备注';
$Definition['Upload'] = '上传';
$Definition['IP Address'] = 'IP地址';
$Definition['BanType'] = '屏蔽类型';
$Definition['Ban Value'] = '屏蔽内容';
$Definition['permalink'] = '传送门';
$Definition['This user has not made any discussions yet.'] = '该用户没有发表过任何帖子';
$Definition['This user has not commented yet.'] = '该用户还没有评论过任何帖子';
$Definition['TermsOfService'] = ''.$SiteName.'服务条款';
$Definition['TermsOfServiceText'] = ' 
服务条款<br>
当您申请用户时，表示您已经同意遵守本规章。 <br>
欢迎您加入本站点参加交流和讨论，本站点为公共论坛，为维护网上公共秩序和社会稳定，请您自觉遵守以下条款： <br>
<br>
一、不得利用本站危害国家安全、泄露国家秘密，不得侵犯国家社会集体的和公民的合法权益，不得利用本站制作、复制和传播下列信息：<br>
　 （一）煽动抗拒、破坏宪法和法律、行政法规实施的；<br>
　（二）煽动颠覆国家政权，推翻社会主义制度的；<br>
　（三）煽动分裂国家、破坏国家统一的；<br>
　（四）煽动民族仇恨、民族歧视，破坏民族团结的；<br>
　（五）捏造或者歪曲事实，散布谣言，扰乱社会秩序的；<br>
　（六）宣扬封建迷信、淫秽、色情、赌博、暴力、凶杀、恐怖、教唆犯罪的；<br>
　（七）公然侮辱他人或者捏造事实诽谤他人的，或者进行其他恶意攻击的；<br>
　（八）损害国家机关信誉的；<br>
　（九）其他违反宪法和法律行政法规的；<br>
　（十）进行商业广告行为的。<br>
<br>
二、互相尊重，对自己的言论和行为负责。<br>
三、禁止在申请用户时使用相关本站的词汇，或是带有侮辱、毁谤、造谣类的或是有其含义的各种语言进行注册用户，否则我们会将其删除。<br>
四、禁止以任何方式对本站进行各种破坏行为。<br>
五、如果您有违反国家相关法律法规的行为，本站概不负责，您的登录论坛信息均被记录无疑，必要时，我们会向相关的国家管理部门提供此类信息。<br>
<br>
  '.$SiteName;